platform :ios, "8.0"

pod "BDDROneFingerZoomGestureRecognizer"
pod "INTULocationManager"
pod "Firebase"
pod "JTSImageViewController"
pod "Foursquare-API-v2"
pod "Reachability"
pod "SWTableViewCell"
pod "FlickrKit"
pod "AFNetworking/UIKit"